### ISSUE TITLE
Crashed on attempting to attack

### ISSUE THREAD

**Issue by MeleeGamer** [RhenaudTheLukark/CreateYourKris#22]
When I tried to attack a Poseur, CYF crashed, showing this error message.
![image](https://github.com/RhenaudTheLukark/CreateYourKris/assets/112276077/1505001d-5921-4042-9b8c-af5c7e95c7cd)

**Comment by RhenaudTheLukark** [comment]
This issue has been solved a long time ago and a fix is available on the Discord server, but I'll post it here so it's easier to access.

Following CYF 0.6.6's release, I have to say all CYK mods will not be compatible with that new version because of how CYK has been implemented.
CYK looks for a variable named `UI` to know whether the current entity script is a player or not, however CYF 0.6.6 added a *UI object*, so it always exists.
The latest change I made to CYK prevented that bug, but if you want older releases of CYK to work on CYF 0.6.6 and onwards, you will have to add that change as well!

Here are the steps you want to take:
- Open the file `Lua/Libraries/CYK/EntityManager.lua`
- Locate the code in [this screenshot](https://cdn.discordapp.com/attachments/570771293117480974/983483840234422352/unknown.png) and add the lines in green in the screenshot below
- Voilà! The CYK mod should be available for CYF 0.6.6!
